### ISSUE TITLE
defmt error trying to install as per instructions

### ISSUE THREAD

**Issue by dhylands** [knurling-rs/app-template#18]
I tried to do the following:
```
 cargo install \
    --git https://github.com/knurling-rs/probe-run \
    --branch main \
    --features defmt --force
cargo install cargo-generate --force
cargo install flip-link --force
cargo generate \
    --git https://github.com/knurling-rs/app-template \
    --branch main \
    --name knurling-template
```
I then performed the edits suggested from the README.md file: https://github.com/knurling-rs/app-template

and when I do:
```
cargo run --bin hello
```
I get the following error:
```
     Running `probe-run --chip nRF52840_xxAA --defmt target/thumbv7em-none-eabihf/debug/hello`
Error: defmt version mismatch (firmware is using 148009e3bb1d99b5a1938a1a816ad0b0b6423aeb, host is using 28c1afb4d3bad747ef47737a83f5c8b13928cb8a); are you using the same git version of defmt and related tools?
Try `cargo install`-ing the latest git version of `probe-run` AND updating your project's `Cargo.lock` with `cargo update`
```
I even did cargo uninstall probe-run and reran the install command above with no change.

**Comment by dhylands** [comment]
It looks like the problem is the Cargo.lock file in probe-run:
https://github.com/knurling-rs/probe-run/blob/056d958a557103a0176b7c50090717c6ccb0f90f/Cargo.lock#L240

**Comment by dhylands** [comment]
Which goes back to: https://github.com/knurling-rs/probe-run/blob/056d958a557103a0176b7c50090717c6ccb0f90f/Cargo.toml#L18

**Comment by dhylands** [comment]
I created a PR in probe-run which will address this issue: https://github.com/knurling-rs/probe-run/pull/90

**Comment by jonas-schievink** [comment]
I think we need to pin the versions used by the template's `defmt` dependency, and should use `cargo install --rev` to pin the `probe-run` commit. Otherwise this will keep breaking as soon as defmt commits are pushed.

**Comment by albertskog** [comment]
Ran in to this today and it looks like the commit has changed because my error message is different:
```
Error: defmt version mismatch (firmware is using 77bef853e2f18fb7eaac102f4dfffd569ae0ca97, host is using a6dc0904872cd3f4aee5125dffc17723df3c9393); are you using the same git version of defmt and related tools?
```

For the impatient, here is a workaround (exact path and SHA may be different depending on what you have checked out):
```
cd ~/.cargo/git/checkouts/probe-run-31a04fec2ca67672/554db6b/
```
Edit `Cargo.toml` and replace `28c1afb` on line 18 and 19 with `77bef85` (or whatever the first seven characters of your firmware's SHA is in the error message)

```
cargo build --release --features defmt
cp target/release/probe-run ../../../../bin/
```

**Comment by davehylands** [comment]
Another way to perhaps address this would be to have a command line option on probe-run which prints out the git hash linked into probe-run, and then use that as part of installing defmt so that the matching version of defmt is installed rather than the latest. This would allow the template to still use the latest version of probe-run rather than pinning to a specific version.

**Comment by japaric** [comment]
I think things have improved since this was reported: we have defmt on crates.io and app-template has instructions to switch a git version known to work with the probe-run you have installed. If you are still running into issues using the git version of defmt please  open a new issue.
